In [54]:
import pandas as pd

#Loading dataset

In [55]:
df=pd.read_csv(r"C:\Users\HAS\Downloads\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [57]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [58]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [59]:
df['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [60]:
df['Churn']=df['Churn'].map({'Yes':1,'No':0})

In [61]:
df['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [62]:
df['Churn']=pd.to_numeric(df['Churn'], errors='coerce')

In [63]:
df['Churn'].isnull().sum()

np.int64(0)

In [66]:
#Feature Engineering

In [ ]:
#Creating tenure groups

In [67]:
df['TenureGroup']=pd.cut(df['tenure'],
                         bins=[0,12,24,48,72],
                         labels=['0-1 yr', '1-2 yr','2-4 yr', '4-6 yr'])

In [68]:
df[['tenure','TenureGroup']].head()

   tenure TenureGroup
0       1      0-1 yr
1      34      2-4 yr
2       2      0-1 yr
3      45      2-4 yr
4       2      0-1 yr

In [70]:
df['ChargeLevel']=pd.cut(df['MonthlyCharges'],
                         bins=3,
                         labels=['Low','Medium','High'])

In [71]:
df[['MonthlyCharges','ChargeLevel']].head()

   MonthlyCharges ChargeLevel
0           29.85         Low
1           56.95      Medium
2           53.85      Medium
3           42.30         Low
4           70.70      Medium

In [72]:
df.to_csv("cleaned_churn.csv",index=False)